Remove broken pacman command for installing packages
This is a regression from https://github.com/puppetlabs/puppet/commit/d23d6dbfd2e578016441ab292d934b4d74ab436f

During some cleanup, the command

```
pacman pacman --noconfirm --noprogressbar -Sy
```

got modified to:

```
pacman pacman --noconfirm --noprogressbar -S
```

But this isn't a valid command anymore:

```
root@bastelfreak-nb ~ # pacman --noconfirm --noprogressbar -S
error: no targets specified (use -h for help)
root@bastelfreak-nb ~ #
```

The idea was to prevent partial system upgrades while installing new
packages. To do this, the `sync` option was removed from the
installation routine. The correct fix is to remove the command
completely.